### PR TITLE
Add GNU/Hurd and GNU/kFreeBSD with glibc

### PR DESCRIPTION
**Pull request by mirabilos**

### CODE REVIEW

**Comment by BenWiederhake** [comment]
This feels like the hundredth bug in these few lines of code. This is hilarious, especially since the rest of libtgl only works with little endian, so the entire thing is pointless.

I'll replace the file soon-ish.

**Comment by mirabilos** [comment]
So, “that works”, did you test that on Debian GNU/kFreeBSD and Debian GNU/Hurd?

With this trivial check, it builds (at least on kfreebsd; hurd needs https://github.com/majn/tgl/pull/35 additionally, and I had not yet tested again) at least…

**Comment by BenWiederhake** [comment]
I'll merge this for now, and "someday™" I'll look at switching to [this library](https://github.com/BenWiederhake/portable-endian). (The reason why I'm so sure that it's better is that the code does not even make an attempt to detect OS, headers, macros, architecture, kernel, builtins, or anything else.)

**Comment by mirabilos** [comment]
Ben Wiederhake dixit:

>I'll merge this for now, and "someday™" I'll look at switching to [this
>library](https://github.com/BenWiederhake/portable-endian).

OK, thanks. That will improve the chance that the next release
will work as-is on the Hurd ;-)

>(The reason why I'm so sure that it's better is that the code does not
>even make an attempt to detect OS, headers, macros, architecture,
>kernel, builtins, or anything else.)

Ah, right.

**Pull request merged**
